version: "3.8"

services:
  postgres:
    build : .
    image : nfl_postgres
    restart: always
    container_name: nfl_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    shm_size: 1g
    volumes:
      - ./nflpgdata:/data

volumes:
  db:
    driver: local