version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    volumes:
          - ./nflpgdata:/data
    environment:
      - PGDATA=/data
    env_file:
      - .env
      
volumes:
  nflpgdata:
    name: nflpgdata
    external: true
      

